In [20]:
import os
import csv
from bs4 import BeautifulSoup
from pathlib import Path
import pandas as pd

In [21]:
def extract_abstract(soup):
    """Extrae el abstract del HTML de PubMed Central"""
    abstract_text = ""
    
    # Buscar en diferentes posibles estructuras
    abstract_section = soup.find('div', class_='abstract') or \
                      soup.find('section', {'id': 'abstract'}) or \
                      soup.find('div', {'id': 'abstract'})
    
    if abstract_section:
        # Remover el título "Abstract" si existe
        for title in abstract_section.find_all(['h2', 'h3', 'title']):
            title.decompose()
        abstract_text = abstract_section.get_text(separator=' ', strip=True)
    
    return abstract_text

def extract_conclusions(soup):
    """Extrae las conclusiones del HTML de PubMed Central"""
    conclusions_text = ""
    
    # Buscar secciones de conclusiones con diferentes nombres posibles
    possible_headers = ['conclusion', 'conclusions', 'concluding remarks', 
                       'summary', 'conclusions and perspectives']
    
    for header in soup.find_all(['h2', 'h3', 'h4']):
        header_text = header.get_text().lower().strip()
        if any(term in header_text for term in possible_headers):
            # Obtener el contenido después del header
            conclusion_section = header.find_next_sibling()
            if conclusion_section:
                conclusions_text = conclusion_section.get_text(separator=' ', strip=True)
                break
    
    # También buscar por ID o clase
    if not conclusions_text:
        conclusion_div = soup.find('div', {'id': lambda x: x and 'conclusion' in x.lower()}) or \
                        soup.find('section', {'id': lambda x: x and 'conclusion' in x.lower()})
        if conclusion_div:
            conclusions_text = conclusion_div.get_text(separator=' ', strip=True)
    
    return conclusions_text

def process_pmc_htmls(folder_path='pmc_htmls', output_csv='pubmed_data.csv'):
    """Procesa todos los archivos HTML en la carpeta y crea el CSV"""
    
    folder = Path(folder_path)
    if not folder.exists():
        print(f"Error: La carpeta '{folder_path}' no existe")
        return
    
    results = []
    html_files = list(folder.glob('*.html'))
    
    if not html_files:
        print(f"No se encontraron archivos HTML en '{folder_path}'")
        return
    
    print(f"Procesando {len(html_files)} archivos...")
    
    for html_file in html_files:
        # Extraer el PMC ID del nombre del archivo (sin .html)
        pmc_id = html_file.stem
        
        try:
            with open(html_file, 'r', encoding='utf-8') as f:
                html_content = f.read()
            
            soup = BeautifulSoup(html_content, 'html.parser')
            
            abstract = extract_abstract(soup)
            conclusions = extract_conclusions(soup)
            
            results.append({
                'pmc_id': pmc_id,
                'abstract': abstract,
                'conclusions': conclusions
            })
            
            print(f"✓ Procesado: {pmc_id}")
            
        except Exception as e:
            print(f"✗ Error procesando {pmc_id}: {str(e)}")
            results.append({
                'pmc_id': pmc_id,
                'abstract': '',
                'conclusions': ''
            })
    
    # Escribir resultados al CSV
    with open(output_csv, 'w', newline='', encoding='utf-8') as csvfile:
        fieldnames = ['pmc_id', 'abstract', 'conclusions']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        
        writer.writeheader()
        writer.writerows(results)
    
    print(f"\n✓ Archivo CSV creado: {output_csv}")
    print(f"Total de artículos procesados: {len(results)}")

if __name__ == "__main__":
    # Ejecutar el procesamiento
    process_pmc_htmls()
    
    # Si quieres personalizar las rutas:
    # process_pmc_htmls(folder_path='mi_carpeta', output_csv='mi_resultado.csv')

Procesando 572 archivos...
✓ Procesado: PMC11999716
✓ Procesado: PMC7076552
✓ Procesado: PMC4469364
✓ Procesado: PMC3251573
✓ Procesado: PMC10503492
✓ Procesado: PMC9953463
✓ Procesado: PMC5826609
✓ Procesado: PMC4917201
✓ Procesado: PMC9743659
✓ Procesado: PMC8754149
✓ Procesado: PMC10764921
✓ Procesado: PMC8396460
✓ Procesado: PMC9832585
✓ Procesado: PMC10285634
✓ Procesado: PMC10996920
✓ Procesado: PMC3166430
✓ Procesado: PMC4064004
✓ Procesado: PMC4321547
✓ Procesado: PMC10020673
✓ Procesado: PMC6379395
✓ Procesado: PMC7778922
✓ Procesado: PMC11470607
✓ Procesado: PMC3792163
✓ Procesado: PMC7561690
✓ Procesado: PMC3603133
✓ Procesado: PMC5460135
✓ Procesado: PMC11942576
✓ Procesado: PMC3869332
✓ Procesado: PMC11339457
✓ Procesado: PMC5568470
✓ Procesado: PMC11892206
✓ Procesado: PMC6036641
✓ Procesado: PMC3947616
✓ Procesado: PMC10848226
✓ Procesado: PMC8234954
✓ Procesado: PMC8185232
✓ Procesado: PMC7599661
✓ Procesado: PMC4085587
✓ Procesado: PMC4490751
✓ Procesado: PMC7118179
✓ Procesado: PMC6343501
✓ Procesado: PMC4095884
✓ Procesado: PMC3092937
✓ Procesado: PMC11593819
✓ Procesado: PMC3067220
✓ Procesado: PMC7530743
✓ Procesado: PMC3851762
✓ Procesado: PMC8067245
✓ Procesado: PMC7998608
✓ Procesado: PMC6387434
✓ Procesado: PMC9389742
✓ Procesado: PMC10719374
✓ Procesado: PMC12040010
✓ Procesado: PMC9605285
✓ Procesado: PMC3981873
✓ Procesado: PMC7787258
✓ Procesado: PMC8169688
✓ Procesado: PMC8217198
✓ Procesado: PMC5648920
✓ Procesado: PMC4507784
✓ Procesado: PMC5047659
✓ Procesado: PMC4427280
✓ Procesado: PMC11233762
✓ Procesado: PMC11166952
✓ Procesado: PMC8513672
✓ Procesado: PMC11088941
✓ Procesado: PMC9108708
✓ Procesado: PMC10800490
✓ Procesado: PMC10607959
✓ Procesado: PMC7067979
✓ Procesado: PMC3818365
✓ Procesado: PMC8739323
✓ Procesado: PMC2910419
✓ Procesado: PMC6753329
✓ Procesado: PMC9400218
✓ Procesado: PMC5498037
✓ Procesado: PMC6426649
✓ Procesado: PMC5389344
✓ Procesado: PMC12008199
✓ Procesado: PMC7000411
✓ Procesado: PMC9144607
✓ Procesado: PMC4290804
✓ Procesado: PMC11953390
✓ Procesado: PMC2925951
✓ Procesado: PMC7828077
✓ Procesado: PMC5666744
✓ Procesado: PMC11166946
✓ Procesado: PMC8441986
✓ Procesado: PMC3133089
✓ Procesado: PMC4379453
✓ Procesado: PMC3665236
✓ Procesado: PMC6126739
✓ Procesado: PMC7393961
✓ Procesado: PMC5515514
✓ Procesado: PMC3002170
✓ Procesado: PMC8211661
✓ Procesado: PMC7261848
✓ Procesado: PMC7940393
✓ Procesado: PMC10487739
✓ Procesado: PMC10233975
✓ Procesado: PMC11386075
✓ Procesado: PMC3329368
✓ Procesado: PMC11659408
✓ Procesado: PMC8024390
✓ Procesado: PMC6081456
✓ Procesado: PMC4050424
✓ Procesado: PMC4653813
✓ Procesado: PMC10813126
✓ Procesado: PMC4631774
✓ Procesado: PMC6013642
✓ Procesado: PMC5580210
✓ Procesado: PMC9693084
✓ Procesado: PMC5114340
✓ Procesado: PMC11988870
✓ Procesado: PMC7890410
✓ Procesado: PMC7733874
✓ Procesado: PMC8953707
✓ Procesado: PMC5748516
✓ Procesado: PMC5677518
✓ Procesado: PMC11167039
✓ Procesado: PMC4103452
✓ Procesado: PMC4187989
✓ Procesado: PMC9746133
✓ Procesado: PMC3350920
✓ Procesado: PMC4618186
✓ Procesado: PMC8323809
✓ Procesado: PMC10432549
✓ Procesado: PMC3040128
✓ Procesado: PMC6222041
✓ Procesado: PMC5866446
✓ Procesado: PMC6529585
✓ Procesado: PMC11748630
✓ Procesado: PMC7415877
✓ Procesado: PMC5421618
✓ Procesado: PMC11166909
✓ Procesado: PMC11579474
✓ Procesado: PMC2915878
✓ Procesado: PMC11053165
✓ Procesado: PMC7190111
✓ Procesado: PMC4110898
✓ Procesado: PMC9583032
✓ Procesado: PMC6599637
✓ Procesado: PMC6372189
✓ Procesado: PMC10142442
✓ Procesado: PMC10410709
✓ Procesado: PMC10284894
✓ Procesado: PMC8430797
✓ Procesado: PMC8539686
✓ Procesado: PMC6188462
✓ Procesado: PMC3659353
✓ Procesado: PMC6204695
✓ Procesado: PMC6813909
✓ Procesado: PMC7610290
✓ Procesado: PMC8904044
✓ Procesado: PMC6560652
✓ Procesado: PMC3187170
✓ Procesado: PMC4936552
✓ Procesado: PMC3558598
✓ Procesado: PMC11166662
✓ Procesado: PMC5515519
✓ Procesado: PMC5578834
✓ Procesado: PMC6130020
✓ Procesado: PMC9267413
✓ Procesado: PMC6289879
✓ Procesado: PMC2897429
✓ Procesado: PMC4135744
✓ Procesado: PMC5864415
✓ Procesado: PMC11166981
✓ Procesado: PMC9163032
✓ Procesado: PMC11451251
✓ Procesado: PMC7414185
✓ Procesado: PMC6889863
✓ Procesado: PMC7607443
✓ Procesado: PMC10793275
✓ Procesado: PMC7756143
✓ Procesado: PMC11094041
✓ Procesado: PMC11127935
✓ Procesado: PMC10960378
✓ Procesado: PMC11046949
✓ Procesado: PMC9445043
✓ Procesado: PMC3890248
✓ Procesado: PMC11940681
✓ Procesado: PMC11477029
✓ Procesado: PMC5865701
✓ Procesado: PMC10470837
✓ Procesado: PMC3508904
✓ Procesado: PMC6547757
✓ Procesado: PMC11484870
✓ Procesado: PMC5659752
✓ Procesado: PMC6124165
✓ Procesado: PMC6091969
✓ Procesado: PMC8005752
✓ Procesado: PMC8220224
✓ Procesado: PMC5805884
✓ Procesado: PMC5933128
✓ Procesado: PMC4453782
✓ Procesado: PMC9862956
✓ Procesado: PMC6706399
✓ Procesado: PMC8131644
✓ Procesado: PMC6348315
✓ Procesado: PMC10504369
✓ Procesado: PMC11930778
✓ Procesado: PMC5026643
✓ Procesado: PMC10780891
✓ Procesado: PMC6689164
✓ Procesado: PMC8886715
✓ Procesado: PMC5672023
✓ Procesado: PMC3856860
✓ Procesado: PMC8364238
✓ Procesado: PMC5910807
✓ Procesado: PMC7996555
✓ Procesado: PMC11833055
✓ Procesado: PMC5488280
✓ Procesado: PMC3190158
✓ Procesado: PMC9865768
✓ Procesado: PMC4398884
✓ Procesado: PMC4012541
✓ Procesado: PMC3066201
✓ Procesado: PMC10831389
✓ Procesado: PMC5491145
✓ Procesado: PMC4411111
✓ Procesado: PMC5821596
✓ Procesado: PMC5736159
✓ Procesado: PMC10846184
✓ Procesado: PMC8896891
✓ Procesado: PMC5504618
✓ Procesado: PMC7324008
✓ Procesado: PMC9105288
✓ Procesado: PMC5587110
✓ Procesado: PMC11362537
✓ Procesado: PMC12034070
✓ Procesado: PMC9098553
✓ Procesado: PMC4647464
✓ Procesado: PMC3615599
✓ Procesado: PMC3545801
✓ Procesado: PMC6452512
✓ Procesado: PMC6952069
✓ Procesado: PMC4985531
✓ Procesado: PMC7733933
✓ Procesado: PMC7314936
✓ Procesado: PMC11126634
✓ Procesado: PMC11324864
✓ Procesado: PMC11166648
✓ Procesado: PMC4902601
✓ Procesado: PMC7667275
✓ Procesado: PMC8450295
✓ Procesado: PMC6548323
✓ Procesado: PMC6062551
✓ Procesado: PMC9365836
✓ Procesado: PMC9031868
✓ Procesado: PMC3748764
✓ Procesado: PMC10605753
✓ Procesado: PMC5288125
✓ Procesado: PMC3422896
✓ Procesado: PMC5896955
✓ Procesado: PMC6204554
✓ Procesado: PMC4033213
✓ Procesado: PMC6141014
✓ Procesado: PMC7954810
✓ Procesado: PMC11929063
✓ Procesado: PMC7326050
✓ Procesado: PMC4945788
✓ Procesado: PMC5116466
✓ Procesado: PMC7484075
✓ Procesado: PMC8509868
✓ Procesado: PMC11673879
✓ Procesado: PMC7064724
✓ Procesado: PMC5515506
✓ Procesado: PMC5443495
✓ Procesado: PMC9617909
✓ Procesado: PMC5415411
✓ Procesado: PMC4405755
✓ Procesado: PMC8421509
✓ Procesado: PMC11747068
✓ Procesado: PMC6280456
✓ Procesado: PMC4152162
✓ Procesado: PMC5181587
✓ Procesado: PMC11166968
✓ Procesado: PMC8444978
✓ Procesado: PMC9856674
✓ Procesado: PMC2991213
✓ Procesado: PMC7937622
✓ Procesado: PMC11263583
✓ Procesado: PMC10712242
✓ Procesado: PMC5523082
✓ Procesado: PMC3012082
✓ Procesado: PMC6321533
✓ Procesado: PMC8518694
✓ Procesado: PMC9964234
✓ Procesado: PMC9640571
✓ Procesado: PMC6597714
✓ Procesado: PMC4187166
✓ Procesado: PMC5460236
✓ Procesado: PMC11988970
✓ Procesado: PMC11492218
✓ Procesado: PMC7825584
✓ Procesado: PMC11166967
✓ Procesado: PMC8475764
✓ Procesado: PMC11500582
✓ Procesado: PMC5955502
✓ Procesado: PMC7055474
✓ Procesado: PMC4042434
✓ Procesado: PMC7303416
✓ Procesado: PMC8086211
✓ Procesado: PMC8269219
✓ Procesado: PMC3747666
✓ Procesado: PMC2824534
✓ Procesado: PMC5485990
✓ Procesado: PMC7285199
✓ Procesado: PMC6908503
✓ Procesado: PMC4378170
✓ Procesado: PMC6710492
✓ Procesado: PMC6201722
✓ Procesado: PMC7339929
✓ Procesado: PMC7382458
✓ Procesado: PMC11831363
✓ Procesado: PMC5219934
✓ Procesado: PMC10789781
✓ Procesado: PMC3570223
✓ Procesado: PMC9410522
✓ Procesado: PMC11271499
✓ Procesado: PMC7264257
✓ Procesado: PMC11941215
✓ Procesado: PMC12034939
✓ Procesado: PMC4169763
✓ Procesado: PMC11701653
✓ Procesado: PMC10751425
✓ Procesado: PMC7870178
✓ Procesado: PMC6143729
✓ Procesado: PMC4624184
✓ Procesado: PMC4309212
✓ Procesado: PMC12031868
✓ Procesado: PMC11487192
✓ Procesado: PMC7555395
✓ Procesado: PMC8104057
✓ Procesado: PMC8133610
✓ Procesado: PMC4150462
✓ Procesado: PMC11063234
✓ Procesado: PMC5052530
✓ Procesado: PMC11888247
✓ Procesado: PMC10774393
✓ Procesado: PMC7162976
✓ Procesado: PMC8412175
✓ Procesado: PMC9547011
✓ Procesado: PMC9695138
✓ Procesado: PMC9287483
✓ Procesado: PMC5666834
✓ Procesado: PMC3868799
✓ Procesado: PMC11302229
✓ Procesado: PMC3564669
✓ Procesado: PMC7595942
✓ Procesado: PMC4340379
✓ Procesado: PMC11166646
✓ Procesado: PMC8890767
✓ Procesado: PMC7010715
✓ Procesado: PMC4052902
✓ Procesado: PMC6251167
✓ Procesado: PMC5460263
✓ Procesado: PMC7555797
✓ Procesado: PMC4776492
✓ Procesado: PMC9953055
✓ Procesado: PMC4309301
✓ Procesado: PMC10889206
✓ Procesado: PMC6069985
✓ Procesado: PMC6981245
✓ Procesado: PMC9116463
✓ Procesado: PMC6240453
✓ Procesado: PMC7317102
✓ Procesado: PMC7503278
✓ Procesado: PMC4349987
✓ Procesado: PMC4035928
✓ Procesado: PMC4337661
✓ Procesado: PMC5460239
✓ Procesado: PMC11166948
✓ Procesado: PMC3457586
✓ Procesado: PMC4116675
✓ Procesado: PMC10772081
✓ Procesado: PMC5201052
✓ Procesado: PMC3982735
✓ Procesado: PMC10472590
✓ Procesado: PMC3639165
✓ Procesado: PMC8875396
✓ Procesado: PMC5600826
✓ Procesado: PMC3554398
✓ Procesado: PMC10390562
✓ Procesado: PMC5026642
✓ Procesado: PMC5771473
✓ Procesado: PMC10715203
✓ Procesado: PMC6747492
✓ Procesado: PMC9784906
✓ Procesado: PMC3509447
✓ Procesado: PMC4642138
✓ Procesado: PMC4118556
✓ Procesado: PMC11022651
✓ Procesado: PMC8879990
✓ Procesado: PMC5454470
✓ Procesado: PMC10308117
✓ Procesado: PMC7251690
✓ Procesado: PMC8716943
✓ Procesado: PMC11167060
✓ Procesado: PMC11096397
✓ Procesado: PMC10063413
✓ Procesado: PMC4211383
✓ Procesado: PMC9706465
✓ Procesado: PMC6386654
✓ Procesado: PMC9111996
✓ Procesado: PMC6746706
✓ Procesado: PMC11869762
✓ Procesado: PMC5614317
✓ Procesado: PMC9098231
✓ Procesado: PMC6865368
✓ Procesado: PMC4430214
✓ Procesado: PMC3005423
✓ Procesado: PMC6057834
✓ Procesado: PMC10027818
✓ Procesado: PMC9258157
✓ Procesado: PMC3258067
✓ Procesado: PMC8274610
✓ Procesado: PMC9241228
✓ Procesado: PMC6945029
✓ Procesado: PMC3901686
✓ Procesado: PMC9737020
✓ Procesado: PMC10342025
✓ Procesado: PMC4964660
✓ Procesado: PMC12021249
✓ Procesado: PMC10386755
✓ Procesado: PMC6359015
✓ Procesado: PMC3242767
✓ Procesado: PMC9701605
✓ Procesado: PMC11167097
✓ Procesado: PMC11166911
✓ Procesado: PMC3647661
✓ Procesado: PMC5391430
✓ Procesado: PMC4228280
✓ Procesado: PMC6048781
✓ Procesado: PMC5397022
✓ Procesado: PMC7467030
✓ Procesado: PMC10025027
✓ Procesado: PMC6638264
✓ Procesado: PMC5470433
✓ Procesado: PMC6462350
✓ Procesado: PMC6165321
✓ Procesado: PMC5817088
✓ Procesado: PMC7138367
✓ Procesado: PMC3503204
✓ Procesado: PMC3593973
✓ Procesado: PMC8044432
✓ Procesado: PMC9576569
✓ Procesado: PMC3936501
✓ Procesado: PMC4136787
✓ Procesado: PMC9487896
✓ Procesado: PMC11969330
✓ Procesado: PMC11403809
✓ Procesado: PMC5387210
✓ Procesado: PMC9695374
✓ Procesado: PMC11166969
✓ Procesado: PMC5018776
✓ Procesado: PMC3630201
✓ Procesado: PMC7029147
✓ Procesado: PMC7756144
✓ Procesado: PMC6590338
✓ Procesado: PMC8099722
✓ Procesado: PMC11850895
✓ Procesado: PMC11166944
✓ Procesado: PMC7358545
✓ Procesado: PMC5515520
✓ Procesado: PMC10138634
✓ Procesado: PMC2913424
✓ Procesado: PMC5666799
✓ Procesado: PMC6213004
✓ Procesado: PMC8493566
✓ Procesado: PMC6371294
✓ Procesado: PMC10528075
✓ Procesado: PMC5515531
✓ Procesado: PMC10144393
✓ Procesado: PMC4494396
✓ Procesado: PMC8816950
✓ Procesado: PMC9502502
✓ Procesado: PMC6876156
✓ Procesado: PMC11167063
✓ Procesado: PMC7072278
✓ Procesado: PMC9549344
✓ Procesado: PMC10264680
✓ Procesado: PMC3044105
✓ Procesado: PMC3177255
✓ Procesado: PMC7987364
✓ Procesado: PMC10261121
✓ Procesado: PMC4750446
✓ Procesado: PMC10058394
✓ Procesado: PMC3430326
✓ Procesado: PMC5045078
✓ Procesado: PMC11357997
✓ Procesado: PMC4462657
✓ Procesado: PMC8537831
✓ Procesado: PMC7677455
✓ Procesado: PMC4682325
✓ Procesado: PMC6447593
✓ Procesado: PMC8012687
✓ Procesado: PMC4960141
✓ Procesado: PMC4826010
✓ Procesado: PMC9699585
✓ Procesado: PMC9582271
✓ Procesado: PMC9293686
✓ Procesado: PMC5958250
✓ Procesado: PMC3337602
✓ Procesado: PMC11166943
✓ Procesado: PMC5477841
✓ Procesado: PMC11166655
✓ Procesado: PMC11353732
✓ Procesado: PMC8213760
✓ Procesado: PMC8932657
✓ Procesado: PMC6339989
✓ Procesado: PMC6137544
✓ Procesado: PMC9023564
✓ Procesado: PMC9146534
✓ Procesado: PMC4411250
✓ Procesado: PMC7235020
✓ Procesado: PMC10030976
✓ Procesado: PMC5899691
✓ Procesado: PMC11357981
✓ Procesado: PMC5761896
✓ Procesado: PMC7171750
✓ Procesado: PMC3289768
✓ Procesado: PMC3774184
✓ Procesado: PMC9139491
✓ Procesado: PMC6131065
✓ Procesado: PMC6275019
✓ Procesado: PMC5286820
✓ Procesado: PMC10797188
✓ Procesado: PMC10628120
✓ Procesado: PMC7907224
✓ Procesado: PMC6915713
✓ Procesado: PMC9503880
✓ Procesado: PMC6615562
✓ Procesado: PMC5810432
✓ Procesado: PMC4096993
✓ Procesado: PMC4896697
✓ Procesado: PMC4385880
✓ Procesado: PMC3502426
✓ Procesado: PMC3962621
✓ Procesado: PMC8183356
✓ Procesado: PMC10344948
✓ Procesado: PMC9861679
✓ Procesado: PMC10414970
✓ Procesado: PMC8113475
✓ Procesado: PMC6985101
✓ Procesado: PMC7829349
✓ Procesado: PMC7943786
✓ Procesado: PMC4161659
✓ Procesado: PMC6366624
✓ Procesado: PMC7012842
✓ Procesado: PMC11998595
✓ Procesado: PMC2998437
✓ Procesado: PMC3838407
✓ Procesado: PMC8468678
✓ Procesado: PMC11166937
✓ Procesado: PMC11222149
✓ Procesado: PMC8260663
✓ Procesado: PMC8191917
✓ Procesado: PMC8671758
✓ Procesado: PMC10370681
✓ Procesado: PMC10926278
✓ Procesado: PMC3911009
✓ Procesado: PMC4653058
✓ Procesado: PMC7516158
✓ Procesado: PMC8400407
✓ Procesado: PMC10422843
✓ Procesado: PMC5552977
✓ Procesado: PMC5132293
✓ Procesado: PMC4923109
✓ Procesado: PMC5996828
✓ Procesado: PMC6337482

✓ Archivo CSV creado: pubmed_data.csv
Total de artículos procesados: 572

In [26]:
df = pd.read_csv("pubmed_data.csv")
df.head()

        pmc_id  abstract                                        conclusions
0  PMC11999716       NaN  The microbiome of the Gowanus Canal is a biote...
1   PMC7076552       NaN  As the volume of spaceflight omics-level data ...
2   PMC4469364       NaN                                                NaN
3   PMC3251573       NaN  Plasmids Size (bp) Inc group GC% N° ORFs Start...
4  PMC10503492       NaN  Spaceflight poses risks to the central nervous...

In [23]:
dfr = pd.read_csv("articles_data_updated.csv")
dfr["Conclusions"] = df["conclusions"]
dfr.head()

,PMC_ID,Title,Authors,Introduction,Development/Methods,Results,Discussion,References_Count,References,Conclusions
0,PMC4136787,Mice in Bion-M 1 Space Mission: Training and S...,Alexander Andreev-Andrievskiy; Anfisa Popova; ...,"After a 16-year hiatus, Russia resumed in 2013...",The study was approved by IACUC of MSU Institu...,Living conditions for animals considered optim...,Living conditions for animals considered optim...,37,2007 Animals in space Vestnik Rossijskoj Akade...,The microbiome of the Gowanus Canal is a biote...
1,PMC3630201,Microgravity Induces Pelvic Bone Loss through ...,Elizabeth A. Blaber; Natalya Dvorochkin; Chial...,"On Earth, at 1 g, mechanical loading of mammal...",All experimental animal procedures for STS-131...,All flight and ground control mice were observ...,"In this study, we investigated cellular and mo...",74,2000 Historical overview of the Bion project J...,As the volume of spaceflight omics-level data ...
2,PMC11988870,Microgravity and Cellular Biology: Insights in...,Nelson Adolfo López Garzón; María Virginia Pin...,"Microgravity, a condition characterized by min...",A comprehensive literature review was conducte...,NaN,Recent research demonstrates that microgravity...,70,2003 Genetic models in applied physiology: sel...,NaN
3,PMC7998608,Selective Proliferation of Highly Functional A...,Takanobu Mashiko; Koji Kanayama; Natsumi Saito...,Human adipose-derived stem cells (hASCs) are e...,Human lipoaspirates were obtained from 12 heal...,Cells were expanded for three passages before ...,"Through novel advances in cell biology, adult ...",48,2013 Effects of spaceflight and ground recover...,Plasmids Size (bp) Inc group GC% N° ORFs Start...
4,PMC5587110,Microgravity validation of a novel system for ...,Macarena Parra; Jimmy Jung; Travis D. Boone; L...,The ISS National Laboratory is a unique resear...,"In order to validate the system, a number of g...",In order to assess the functionality of PCR in...,One of the major obstacles to space exploratio...,38,2013 Changes in Mouse Thymus and Spleen after ...,Spaceflight poses risks to the central nervous...

In [24]:
# Save the updated DataFrame
dfr.to_csv("articles_data_updated.csv", index=False, encoding='utf-8')

In [25]:
dfr.head()

,PMC_ID,Title,Authors,Introduction,Development/Methods,Results,Discussion,References_Count,References,Conclusions
0,PMC4136787,Mice in Bion-M 1 Space Mission: Training and S...,Alexander Andreev-Andrievskiy; Anfisa Popova; ...,"After a 16-year hiatus, Russia resumed in 2013...",The study was approved by IACUC of MSU Institu...,Living conditions for animals considered optim...,Living conditions for animals considered optim...,37,2007 Animals in space Vestnik Rossijskoj Akade...,The microbiome of the Gowanus Canal is a biote...
1,PMC3630201,Microgravity Induces Pelvic Bone Loss through ...,Elizabeth A. Blaber; Natalya Dvorochkin; Chial...,"On Earth, at 1 g, mechanical loading of mammal...",All experimental animal procedures for STS-131...,All flight and ground control mice were observ...,"In this study, we investigated cellular and mo...",74,2000 Historical overview of the Bion project J...,As the volume of spaceflight omics-level data ...
2,PMC11988870,Microgravity and Cellular Biology: Insights in...,Nelson Adolfo López Garzón; María Virginia Pin...,"Microgravity, a condition characterized by min...",A comprehensive literature review was conducte...,NaN,Recent research demonstrates that microgravity...,70,2003 Genetic models in applied physiology: sel...,NaN
3,PMC7998608,Selective Proliferation of Highly Functional A...,Takanobu Mashiko; Koji Kanayama; Natsumi Saito...,Human adipose-derived stem cells (hASCs) are e...,Human lipoaspirates were obtained from 12 heal...,Cells were expanded for three passages before ...,"Through novel advances in cell biology, adult ...",48,2013 Effects of spaceflight and ground recover...,Plasmids Size (bp) Inc group GC% N° ORFs Start...
4,PMC5587110,Microgravity validation of a novel system for ...,Macarena Parra; Jimmy Jung; Travis D. Boone; L...,The ISS National Laboratory is a unique resear...,"In order to validate the system, a number of g...",In order to assess the functionality of PCR in...,One of the major obstacles to space exploratio...,38,2013 Changes in Mouse Thymus and Spleen after ...,Spaceflight poses risks to the central nervous...